// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBz9ttumzOihhCSk2LYWhCYLbQ3QPELmE',
    appId: '1:10495381934:web:43f1d814188c8a18eff83f',
    messagingSenderId: '10495381934',
    projectId: 'civic-complaint-a8bd5',
    authDomain: 'civic-complaint-a8bd5.firebaseapp.com',
    storageBucket: 'civic-complaint-a8bd5.firebasestorage.app',
    measurementId: 'G-T8FNCPVJM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Mn6fsdG1bzrZbPCvlFFvU4BluFWd2hk',
    appId: '1:10495381934:android:89d457c29ca625aeeff83f',
    messagingSenderId: '10495381934',
    projectId: 'civic-complaint-a8bd5',
    storageBucket: 'civic-complaint-a8bd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4zW4PhhGSTEeP3VmVubAeOmzOBPwlXE',
    appId: '1:10495381934:ios:d2f900c154aa330ceff83f',
    messagingSenderId: '10495381934',
    projectId: 'civic-complaint-a8bd5',
    storageBucket: 'civic-complaint-a8bd5.firebasestorage.app',
    iosBundleId: 'com.example.electricityAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG4zW4PhhGSTEeP3VmVubAeOmzOBPwlXE',
    appId: '1:10495381934:ios:d2f900c154aa330ceff83f',
    messagingSenderId: '10495381934',
    projectId: 'civic-complaint-a8bd5',
    storageBucket: 'civic-complaint-a8bd5.firebasestorage.app',
    iosBundleId: 'com.example.electricityAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8xJnjkljNIkw_d_Vf494YOqMCqKAJ_vQ',
    appId: '1:10495381934:web:3d43edf4fae1cb19eff83f',
    messagingSenderId: '10495381934',
    projectId: 'civic-complaint-a8bd5',
    authDomain: 'civic-complaint-a8bd5.firebaseapp.com',
    storageBucket: 'civic-complaint-a8bd5.firebasestorage.app',
    measurementId: 'G-SMHNJTQRR8',
  );
}
